### PR TITLE
Fixes for typos and minor issues in the pseudo-Rust code

### PR DESCRIPTION
**Pull request by mattheww**
I think these are all simple corrections.

### CODE REVIEW

**Comment by RalfJung** [comment]
Looks good, thanks!
How did you find all these...?

**Comment by RalfJung** [comment]
Also could you squash the commits together a little?

**Comment by mattheww** [comment]
Would you prefer them all in one commit?

Syntax highlighting spotted the missing parens and quotes, the rest just came from reading it slowly.

**Comment by RalfJung** [comment]
One commit works, or 2 commits where 1 is the syntactic things and one contains the `let` reorderings.

**Comment by mattheww** [comment]
I've force-pushed it as a single commit.

**Comment by RalfJung** [comment]
Thanks. :)

**Pull request merged**
