### PR TITLE
make sure our code is warning-free

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by RalfJung** [comment]
@memoryleak47 would be nice to get this to pass... :)

**Comment by memoryleak47** [comment]
As of now we only have
`function ´bytes_valid_for_type´ is never used`
`function ´transmute´ is never used`

I think those functions are intentionally unused.
Do we want to make them `pub`, or add some `#[allow(dead_code)`?

**Comment by RalfJung** [comment]
Yeah makes sense to mark them unused. They are just for demonstration.

Can you open a PR for that, also including the commit from this PR?

**Comment by RalfJung** [comment]
Superseded by https://github.com/RalfJung/minirust/pull/73

**Pull request closed without merging**
